apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: fedora-coreos-next-devel-on-push
  namespace: coreos-tenant
  labels:
    appstudio.openshift.io/application: fedora-coreos-next-devel
    appstudio.openshift.io/component: fedora-coreos-next-devel
    pipelines.appstudio.openshift.io/type: build
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/coreos/fedora-coreos-config?rev={{revision}}
    build.appstudio.redhat.com/cancel-in-progress: "false"
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "next-devel" && !(files.all.all(f, f.matches("ci/buildroot/") || f.matches(".tekton/fcos-buildroot/")))
  creationTimestamp: null
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/konflux-fedora/coreos-tenant/fedora-coreos-{{target_branch}}:{{revision}}
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args-file
    value: build-args.conf
  - name: workingdir-mount
    value: /run/src
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
    - linux/s390x
    - linux/ppc64le
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:ba3c2d68b527da50d06619c34f15341081c3969aa305f181ecb08e40226e3a28
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-coreos-next-devel
