#!/usr/bin/bash
set -euo pipefail
# Podman is dropping support for CNI networking.
# Podman 5 changes: https://fedoraproject.org/wiki/Changes/Podman5
# This script checks if the system nodes are still using CNI
# networking. If so, they will warned to move their nodes to Netavark.

# Change the output color to yellow
warn=$(echo -e '\033[0;33m')
# No color
nc=$(echo -e '\033[0m')

# Podman supports two network backends Netavark and CNI.
# Netavark is the default network backend and was added in
# Podman version 4.0. CNI is deprecated and is removed
# in Podman version 5.0, in preference of Netavark.
podmanBackend=$(podman info --format "{{.Host.NetworkBackend}}")

if [[ $podmanBackend != "netavark" ]]; then
    motd_path=/run/motd.d/35_cni_warning.motd

    cat << EOF > "${motd_path}"
${warn}
##############################################################################
WARNING: Podman is using CNI networking. CNI is deprecated and will be
removed in the upcoming Podman v5.0, in preference of Netavark. To switch
from CNI networking to Netavark, you must run 'podman system reset --force'.
This will delete all of your images, containers, and custom networks.
Depending on your setup it may be preferable to reprovision the whole machine
from the latest images.

To disable this warning, use:
sudo systemctl disable coreos-cni-networking-check.service
##############################################################################
${nc}
EOF
fi
