#!/bin/bash
# kola: { "exclusive": false }
# With pure network defaults no networking should have been propagated
# from the initramfs. This test tries to verify that is the case.
# https://github.com/coreos/fedora-coreos-tracker/issues/696

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Run the test bits (sets the $fail var)
. $KOLA_EXT_DATA/test-net-propagation.sh

if [ -z "${fail:-}" ]; then
    ok "success: no initramfs network propagation for default configuration"
else
    fatal "fail: no initramfs network propagation for default configuration"
fi
