= Auto-updates

Fedora CoreOS provides atomic updates and rollbacks via https://ostree.readthedocs.io/en/latest/[OSTree] deployments.

By default, the OS performs continuous auto-updates via two components:

 * https://github.com/coreos/rpm-ostree[rpm-ostree] handles multiple on-disk OSTree deployments, and it can switch between them at boot-time.
 * https://github.com/coreos/zincati[Zincati] continuously checks for OS updates and applies them via rpm-ostree.

== OS-update finalization

In order to finalize an OS update, a machine needs to perform a reboot.
As this is an invasive action which may cause service disruption, Zincati allows the cluster administrator to control when nodes are allowed to reboot in order to finalize updates.

The following finalization strategies are available:

 * immediately reboot to apply an update, as soon as it is downloaded and staged locally
 * use an external lock-manager to reboot a fleet of machines in a coordinated way

For further documentation on how to configure updates finalization, check Zincati documentation on https://github.com/coreos/zincati/blob/master/docs/usage/updates-strategy.md[updates strategy].
