= Debugging kernel crashes using kdump

== Introduction
kdump is a service that creates crash dumps when there is a kernel crash. It uses https://www.mankier.com/8/kexec[`kexec(8)`] to boot into a secondary kernel (known as a capture kernel), then exports the contents of the kernel's memory (known as a crash dump or vmcore) to the filesystem. The contents of vmcore can then be analyzed to root cause the kernel crash.

Configuring kdump requires setting the `crashkernel` kernel argument and enabling the kdump systemd service. Memory must be reserved for the crash kernel during booting of the first kernel. `crashkernel=auto` generally doesn't reserve enough memory on Fedora CoreOS, so it is recommended to specify `crashkernel=300M`. 

By default, the vmcore will be saved in `/var/crash`. It is also possible to write the dump to some other location on the local system or to send it over the network by editing `/etc/kdump.conf`. For additional information, see https://www.mankier.com/5/kdump.conf[`kdump.conf(5)`] and the comments in `/etc/kdump.conf` and `/etc/sysconfig/kdump`.

== Configuring kdump via Ignition
.Example kdump configuration
[source,yaml,subs="attributes"]
----
variant: fcos
version: {butane-latest-stable-spec}
kernel_arguments:
  should_exist:
  - 'crashkernel=300M'
systemd:
  units:
  - name: kdump.service
    enabled: true
----

== Configuring kdump after initial provision
. Set the crashkernel kernel argument
+
[source, bash]
----
sudo rpm-ostree kargs --append='crashkernel=300M'
----
xref:kernel-args.adoc[More information] on how to modify kargs via `rpm-ostree`.

. Enable the kdump systemd service.
+
[source, bash]
----
sudo systemctl enable kdump.service
----

. Reboot your system.
+
[source, bash]
----
sudo systemctl reboot
----

NOTE: It is highly recommended to test the configuration after setting up the `kdump` service, with extra attention to the amount of memory reserved for the crash kernel. For information on how to test that kdump is properly armed and how to analyze the dump, refer to the https://fedoraproject.org/wiki/How_to_use_kdump_to_debug_kernel_crashes[kdump documentation for Fedora] and https://www.kernel.org/doc/html/latest/admin-guide/kdump/kdump.html[the Linux kernel documentation on kdump].
