:experimental:
= Fedora CoreOS Frequently Asked Questions

If you have other questions than are mentioned here or want to discuss
further, join us in our IRC channel,
irc://irc.freenode.org/#fedora-coreos, or on our new
https://discussion.fedoraproject.org/c/server/coreos[discussion board].
Please refer back here as some questions and answers will likely get
updated.

== What is Fedora CoreOS?

Fedora CoreOS is an automatically updating, minimal, monolithic,
container-focused operating system, designed for clusters but also
operable standalone, optimized for Kubernetes but also great without it.
It aims to combine the best of both CoreOS Container Linux and Fedora
Atomic Host, integrating technology like Ignition from Container Linux
with rpm-ostree and SELinux hardening from Project Atomic. Its goal is
to provide the best container host to run containerized workloads
securely and at scale.

https://discussion.fedoraproject.org/t/launch-faq-what-is-fedora-coreos/40[discuss]

== How does Fedora CoreOS relate to Red Hat CoreOS?

Fedora CoreOS is a freely available, community distribution that is the
upstream basis for Red Hat CoreOS. While Fedora CoreOS embraces a
variety of containerized use cases, Red Hat CoreOS provides a
focused OS for OpenShift, released and life-cycled in tandem
with the platform.

https://discussion.fedoraproject.org/t/launch-faq-how-does-fedora-coreos-relate-to-red-hat-coreos/41[discuss]

== Does Fedora CoreOS replace Container Linux? What happens to CL?

Fedora CoreOS is the official successor to CoreOS Container Linux, but it
is not a drop-in replacement.  CoreOS Container Linux will reach its
https://coreos.com/os/eol/[end of life] on May 26, 2020, and will no longer
receive updates after that date.  For notes on migrating from Container Linux
to Fedora CoreOS, see the xref:migrate-cl.adoc[migration guide].

https://discussion.fedoraproject.org/t/launch-faq-does-fedora-coreos-replace-container-linux-what-happens-to-cl/42[discuss]

== Does Fedora CoreOS replace Fedora Atomic Host? What happens to Fedora Atomic Host and CentOS Atomic Host?

Fedora CoreOS is the official successor to Fedora Atomic Host. The
last Fedora Atomic Host release was version 29, which has now reached
end-of-life.

CentOS Atomic Host will continue producing downstream rebuilds of RHEL
Atomic Host and will align with the end-of-life. The Fedora CoreOS
project will be the consolidation point for the community distributions.
Users are encouraged to move there in the future.

https://discussion.fedoraproject.org/t/launch-faq-does-fedora-coreos-replace-fedora-atomic-host-what-happens-to-fedora-atomic-host-and-centos-atomic-host/43[discuss]

== What happens to Project Atomic?

Project Atomic is an umbrella project consisting of two flavors of
Atomic Host (Fedora and CentOS) as well as various other
container-related projects. Project Atomic as a project name will be
sunset by the end of 2018 with a stronger individual focus on its
successful projects such as Buildah and Cockpit. This merges the
community side of the operating system more effectively with Fedora and
allows for a clearer communication for other community-supported
projects, specifically the well-adopted
https://twitter.com/hashtag/nobigfatdaemons?src=hash[#nobigfatdaemons]
approach of https://github.com/projectatomic/buildah[Buildah] and the
versatile GUI server manager https://cockpit-project.org/[Cockpit].

https://discussion.fedoraproject.org/t/launch-faq-what-happens-to-project-atomic/44/1[discuss]

== What are the communication channels around Fedora CoreOS?

We have the following new communication channels around Fedora CoreOS:

* mailing list:
https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/[coreos@lists.fedoraproject.org]
* #fedora-coreos on IRC Freenode
* forum at https://discussion.fedoraproject.org/c/coreos
* website at https://getfedora.org/coreos/
* Twitter at https://twitter.com/fedora[@fedora] (all Fedora and
other relevant news)

https://discussion.fedoraproject.org/t/launch-faq-what-are-the-communication-channels-around-fedora-coreos/46/1[discuss]

== Technical FAQ

=== Where can I download Fedora CoreOS?

Fedora CoreOS artifacts are available at https://getfedora.org/en/coreos/download/[getfedora.org].

https://discussion.fedoraproject.org/t/launch-faq-where-can-i-download-fedora-coreos/47/1[discuss]

== Does Fedora CoreOS embrace the Container Linux Update Philosophy?

Yes, Fedora CoreOS comes with automatic
updates and regular releases. Multiple update channels are provided
catering to different users' needs. It introduces a new node-update
service based on rpm-ostree technologies, with a server component that
can be optionally self-hosted. Failures that prevent an update from
booting will automatically be reverted.

https://discussion.fedoraproject.org/t/launch-faq-does-fedora-coreos-embrace-the-container-linux-update-philosophy/48/1[discuss]

== How are Fedora CoreOS nodes provisioned? Can I re-use existing cloud-init configurations?

Fedora CoreOS is provisioned with Ignition. However, existing
Ignition configurations will require changes, as the OS configuration
will be different from Container Linux. Existing cloud-init
configurations are not supported and will need to be migrated into their
Ignition equivalent.

https://discussion.fedoraproject.org/t/launch-faq-how-are-fedora-coreos-nodes-provisioned-can-i-re-use-existing-cloud-init-configurations/49/1[discuss]

== How do I migrate from Container Linux to Fedora CoreOS?

Migrations can be accomplished by re-provisioning the machine with
Fedora CoreOS.  For notes on migrating from Container Linux
to Fedora CoreOS, see the xref:migrate-cl.adoc[migration guide].

https://discussion.fedoraproject.org/t/launch-faq-how-do-i-migrate-from-container-linux-to-fedora-coreos/50/1[discuss]

== How do I migrate from Fedora Atomic Host to Fedora CoreOS?

As with Container Linux, the best practice is to re-provision the node, due
to the cloud-init/Ignition transition at least. Since Fedora CoreOS uses
rpm-ostree technology, it may be possible to rebase from Fedora
Atomic Host to Fedora CoreOS, but it is not recommended. It's
preferable to gain experience deploying systems using Ignition so
that they can be re-provisioned easily if needed. For notes on migrating
from Atomic Host to Fedora CoreOS, see the
xref:migrate-ah.adoc[migration guide].

https://discussion.fedoraproject.org/t/launch-faq-how-do-i-migrate-from-fedora-atomic-host-to-fedora-coreos/51/1[discuss]

== Which container runtimes are available on Fedora CoreOS?

Fedora CoreOS includes Docker and podman by default.
Based on community engagement and support this list could
change over time.

https://discussion.fedoraproject.org/t/launch-faq-which-container-runtimes-are-available-on-fedora-coreos/52/1[discuss]

== Which platforms does Fedora CoreOS support?

Fedora CoreOS runs on at least

* Alibaba Cloud,
* AWS,
* Azure,
* GCP,
* OpenStack,
* QEMU,
* VMware,
* and bare-metal systems if installed to disk or network-booted.

https://discussion.fedoraproject.org/t/launch-faq-which-platforms-does-fedora-coreos-support/53/1[discuss]

== Can I run Kubernetes on Fedora CoreOS?

Yes. However, we envision Fedora CoreOS as not including a specific
container orchestrator (or version of Kubernetes) by default — just like
Container Linux and Atomic Host. We will work with the upstream
Kubernetes community on tools (e.g. kubeadm) and best practices for
installing Kubernetes on Fedora CoreOS.

https://discussion.fedoraproject.org/t/launch-faq-can-i-run-kubernetes-on-fedora-coreos/54/1[discuss]

== How do I run custom applications on Fedora CoreOS?

On Fedora CoreOS, containers are the way to install and configure any
software not provided by the base operating system. The package layering
mechanism provided by rpm-ostree will continue to exist for use in
debugging a Fedora CoreOS machine, but we strongly discourage its use.
For more about this, please refer to xref:running-containers.adoc[documentation].

https://discussion.fedoraproject.org/t/launch-faq-how-do-i-run-custom-applications-on-fedora-coreos/55/1[discuss]

== How do I coordinate cluster-wide OS updates? Is locksmith or the Container Linux Update Operator available for Fedora CoreOS?

We have ported the Container Linux Update Operator to use rpm-ostree in
the upstream repo. If you are using Fedora CoreOS outside of a
Kubernetes cluster, you will be able to use upcoming tools to coordinate
updates and reboots.

https://discussion.fedoraproject.org/t/launch-faq-how-do-i-coordinate-cluster-wide-os-updates-is-locksmith-or-the-container-linux-update-operator-available-for-fedora-coreos/56[discuss]

== How do I upload Fedora CoreOS to private AWS EC2 regions?

Fedora CoreOS today is only uploaded to the standard AWS regions. For regions
in other AWS partitions like GovCloud and AWS China, you must upload the images
yourself.

Note that Fedora CoreOS uses a unified BIOS/UEFI partition layout. As such, it
is not compatible with the `aws ec2 import-image` API (for more information,
see https://github.com/openshift/os/pull/396[related discussions]). Instead,
you must use `aws ec2 import-snapshot` combined with `aws ec2 register-image`.

To learn more about these APIs, see the AWS documentation for
https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-import-snapshot.html[importing snapshots]
and
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html#creating-launching-ami-from-snapshot[creating EBS-backed AMIs].

== Can I run containers via docker and podman at the same time?

No. Running containers via `docker` and `podman` at the same time can cause
issues and unexpected behavior. We highly recommend against trying to use them
both at the same time.

It is worth noting that in Fedora CoreOS we have `docker.service`
disabled by default but it is easily started if anything communicates
with the `/var/run/docker.sock` because `docker.socket` is enabled by
default. This means that if a user runs any `docker` command (via
`sudo docker`) then the daemon will be activated. We did this to make
the transition easier for users of Container Linux.

In https://github.com/coreos/fedora-coreos-tracker/issues/408[coreos/fedora-coreos-tracker#408]
it was pointed out that because of socket activation users who are
using `podman` for containers could unintentionally start the docker
daemon. This could weaken the security of the system because of the
interaction of both container runtimes with the firewall on the system.
To prevent making this mistake you can disable `docker` completely by
masking the `docker.service` systemd unit.

.Example fcct config for disabling docker.service
[source, yaml]
----
variant: fcos
version: 1.0.0
systemd:
  units:
    - name: docker.service
      mask: true
----

== Are Fedora CoreOS x86_64 disk images hybrid BIOS+UEFI bootable?

The bare metal images we provide can be used for either BIOS (legacy) boot or UEFI boot,

https://discussion.fedoraproject.org/t/are-fedora-coreos-disk-images-hybrid-bios-uefi-bootable/21911[Discuss]
