:experimental:
= Fedora CoreOS - Getting Started

Fedora CoreOS (FCOS) has no install-time configuration. Every FCOS system begins with a generic disk image. For each deployment mechanism (cloud VM, local VM, bare metal), configuration can be supplied at first boot. FCOS reads and applies the configuration file with https://github.com/coreos/ignition[Ignition]. For cloud deployments, Ignition gathers the configuration via the cloud’s user-data mechanism. In the case of bare metal, Ignition injects the configuration at install time.

NOTE: For more information on configuration, refer to the documentation for xref:producing-ign.adoc[Producing an Ignition File].

== Launching FCOS

=== Launching on Amazon Web Services (AWS)

To launch FCOS on AWS:

. Identify the correct AMI image ID for your region from https://getfedora.org/coreos/download/[the download page]

. Launch the VM using `aws ec2 run-instances`. The Ignition file can be passed to the VM as its https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-add-user-data[user data]. You can skip this step if you just want SSH access; simply pass a https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[registered key name] via `--key-name`. This provides an easy way to test out FCOS without first creating an Ignition configuration.

.Example launching FCOS on AWS using an Ignition configuration file
[source, bash]
----
aws ec2 run-instances <other options> --image-id <ami> --user-data file://example.ign
----

.Example launching FCOS on AWS using a registered SSH key pair
[source, bash]
----
aws ec2 run-instances <other options> --image-id <ami> --key-name my-key
----

While the AWS documentation mentions cloud-init and scripts, FCOS does not support cloud-init or the ability to run scripts from user-data. It accepts only Ignition configuration files.

=== Launching with QEMU or libvirt
. https://getfedora.org/coreos/download/[Download and verify] the latest image suitable for QEMU.

. Uncompress the file. Assuming that the downloaded file is called `fedora-coreos-qemu.qcow2.xz`, the command would be the following:
+
[source, bash]
----
unxz fedora-coreos-qemu.qcow2.xz
----
+
TIP: Make sure that your user has access to `/dev/kvm` (this should already be the case on modern distros), or if `/dev/kvm` is owned by the `kvm` group, adding yourself to that group with `usermod -aG kvm $USER`.

. Launch the VM using `qemu-kvm` or `virt-install`. The Ignition file is passed to the VM via the `-fw_cfg` parameter, which sets the `opt/com.coreos/config` key in the QEMU firmware configuration device. For libvirt, you must pass this through the `--qemu-commandline` argument. You can use `-snapshot` to make `qemu-kvm` allocate temporary storage for the VM, or `qemu-img create` to first create a layered qcow2.
+
.Example launching FCOS with QEMU (temporary storage)
[source, bash]
----
qemu-kvm -m 2048 -cpu host -nographic -snapshot \
	-drive if=virtio,file=fedora-coreos-qemu.qcow2 \
	-fw_cfg name=opt/com.coreos/config,file=path/to/example.ign
----
+
.Example launching FCOS with QEMU (persistent storage)
[source, bash]
----
qemu-img create qcow2 -b fedora-coreos-qemu.qcow2 my-fcos-vm.qcow2
qemu-kvm -m 2048 -cpu host -nographic \
	-drive if=virtio,file=my-fcos-vm.qcow2 \
	-fw_cfg name=opt/com.coreos/config,file=path/to/example.ign
----
+
.Example launching FCOS with virt-install
[source, bash]
----
virt-install --connect qemu:///system -n fcos -r 2048 --os-variant=fedora31 --import \
	--graphics=none --disk size=10,backing_store=/path/to/fedora-coreos-qemu.qcow2 \
	--qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=/path/to/example.ign"
----

NOTE: When using `virt-install`, you must specify absolute paths to the image and the Ignition file.

TIP: If running with SELinux enabled, you may need to change the label of the Ignition file to allow access: `chcon -t svirt_home_t path/to/example.ign`

Once the VM has finished booting, its IP addresses will appear on the serial console. You can then SSH into the FCOS VM as the `core` user:

[source, bash]
----
ssh core@<ip address>
----

== Installing on bare metal

Follow the xref:bare-metal.adoc[Bare Metal Installation Instructions] to install Fedora CoreOS to disk. This procedure injects the specified Ignition configuration at install time.

== Where to report bugs and ask questions

Report bugs to the https://github.com/coreos/fedora-coreos-tracker[Fedora CoreOS Tracker] and ask questions on the `#fedora-coreos` IRC channel on freenode or on the https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/[Fedora CoreOS mailing list].
