:experimental:
= Fedora CoreOS - Getting Started

== Background

Fedora CoreOS (FCOS) has no install-time configuration. Every FCOS system begins with a generic disk image. For each deployment mechanism (bare metal, local VM, or cloud VM), the configuration must be supplied at first boot. This is done via a configuration file and https://github.com/coreos/ignition[Ignition]. For cloud deployments, Ignition gathers the configuration via the cloud’s user-data mechanism. In the case of bare metal, Ignition injects the configuration at install time.

This guide will show you how to launch Fedora CoreOS (FCOS) on AWS, QEMU, and bare metal.

=== Prerequisite
To launch FCOS, you must feed it an Ignition configuration file. To produce an Ignition file, see xref:producing-ign.adoc[Producing an Ignition File].

== Launching Fedora CoreOS

=== Booting on Amazon Web Services (AWS)

To boot FCOS on AWS:

. Go to the https://getfedora.org/coreos/download/[download page] to identify the correct AMI.

. Specify the Ignition configuration file as the https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-add-user-data[user-data].


.Example launching Fedora CoreOS on AWS
[source, bash]
----
aws ec2 run-instances <other options> --image-id <ami> --user-data file://example.ign
----

While the AWS documentation mentions cloud-init and scripts, FCOS accepts only Ignition configuration files. It does not support cloud-init or the ability to run scripts from user-data.

=== Booting with QEMU
. Go to the https://getfedora.org/coreos/download/[download page] to retrieve the latest image suitable for QEMU.

. Uncompress the file. Assuming that the downloaded file is called `fedora-coreos-qemu.qcow2.xz`, the command would be the following:

+
`unxz fedora-coreos-qemu.qcow2.xz`
+
. Ensure the correct ownership of the file:
+
`chown core:kvm fedora-coreos-qemu.qcow2`
+
TIP: The above example assumes that you have created the user named `core` on your local machine. If you did not, replace `core` with the user that will boot FCOS on the local host.

. Specify the Ignition file to the hypervisor. In the case of QEMU, this is done with the `-fw_cfg` parameter. This sets the `opt/com.coreos/config` key in the QEMU firmware configuration device.
+
You must use absolute file paths here. QEMU cannot resolve relative file paths for these options.
+
.Example launching Fedora CoreOS with QEMU
[source,bash]
----
qemu-system-x86_64 -machine accel=kvm -m 2048 -cpu host -nographic \
	-drive if=virtio,file=path/to/fedora-coreos-qemu.qcow2 \
	-device virtio-rng-pci \
	-fw_cfg name=opt/com.coreos/config,file=path/to/example.ign
----
+
Once the VM has finished booting, its IP addresses will appear on the serial console.

. You can then SSH into the FCOS VM as the `core` user:
+
`ssh core@<ip address>`

== Installing on Bare Metal

Follow the https://github.com/coreos/coreos-installer/[coreos-installer instructions] to install Fedora CoreOS to disk. This procedure injects the specified Ignition configuration at install time.

//To do: Move the install instructions to this page or another page on this site.

== Where to report bugs and ask questions

Report bugs to the https://github.com/coreos/fedora-coreos-tracker[Fedora CoreOS Tracker] and ask questions on the `#fedora-coreos` IRC channel on freenode or on the https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/[Fedora CoreOS mailing list].
