= Getting Started with Fedora CoreOS

== Introduction

=== Streams

There are three Fedora CoreOS (FCOS) update streams available: `stable`, `testing`, and `next`. In general, you will want to use `stable`, but it is recommended to run some machines on `testing` and `next` as well and provide feedback.

Each stream has a canonical URL representing its current state in JSON format, known as "stream metadata". For example, the stream metadata URL for `stable` is: https://builds.coreos.fedoraproject.org/streams/stable.json

For automating Fedora CoreOS installations, it is expected that you will interact with stream metadata. While Fedora CoreOS does automatic in-place updates, it is generally recommended to start provisioning new machines from the latest images.

For more information on using stream metadata, see xref:stream-metadata.adoc[Stream Metadata].
For more about the available streams, see xref:update-streams.adoc[Update Streams].

=== Provisioning Philosophy

Fedora CoreOS does not have a separate install disk. Instead, every instance starts from a generic disk image which is customized on first boot via https://github.com/coreos/ignition[Ignition].

Each platform has specific logic to retrieve and apply the first boot configuration. For cloud deployments, Ignition gathers the configuration via user-data mechanisms. In the case of bare metal, Ignition can fetch its configuration from the disk or from a remote source.

For more information on configuration, refer to the documentation for xref:producing-ign.adoc[Producing an Ignition File].

== Quickstart

=== Booting on a cloud VM (AWS example)

include::getting-started-aws.adoc[]

A more complete example that allows customization is described in xref:provisioning-aws.adoc[].

=== Booting on a local hypervisor (libvirt example)

include::getting-started-libvirt.adoc[]

=== Exploring the OS

Once the VM has finished booting, its IP addresses will appear on the console. By design, there are no hard-coded default credentials.

If you set up an xref:authentication.adoc[SSH key] for the default `core` user, you can SSH into the VM and explore the OS:

[source, bash]
----
ssh core@<ip address>
----

== Getting in touch

We recommend that all users subscribe to the low-volume https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/[coreos-status mailing list] for operational notices related to Fedora CoreOS.

Bugs can be reported to the https://github.com/coreos/fedora-coreos-tracker[Fedora CoreOS Tracker].

For live questions, feel free to reach out in the https://chat.fedoraproject.org/#/room/#coreos:fedoraproject.org[#coreos:fedoraproject.org room on Matrix].

For doubts and longer discussions related to Fedora CoreOS, a https://discussion.fedoraproject.org/tag/coreos[forum] and a https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/[mailing list] are available.
