:experimental:
= Fedora CoreOS - Booting in a VM

== Scope
This guide provides easy, step-by-step instructions to produce a basic Ignition file and use it to launch a Fedora CoreOS VM with QEMU.

Fedora CoreOS Ignition files specify the configuration of FCOS. The process begins with a YAML configuration file. The Fedora CoreOS Configuration Transpiler (FCCT) converts the human-readable YAML file into machine-readable JSON.

TIP: Once FCOS boots and ingests the Ignition file, the configuration is immutable. Therefore, plan your Ignition file with the configuration that you will need.

== Producing the Ignition File
=== Introduction
This section provides instructions to create a basic Ignition file that produces a FCOS user named `fcos_user` able to SSH in with a key.

NOTE: FCOS is fully configurable. For the purpose of learning the process, this section provides instructions for a simple setup. Refer to the FCCT https://github.com/coreos/fcct/blob/master/docs/configuration-v1_0.md[configuration specification] for more a complete list of FCCT configuration options.

The overall steps are as follows:

. Write the Fedora CoreOS Configuration (FCC) file in the YAML format.
. Download and install the Fedora CoreOS Configuration Transpiler (fcct).
. Use fcct to convert the human-readable YAML FCC file into a machine-readable JSON Ignition file.

=== Create local user
Create the `fcos_user` on your local machine and generate an SSH key for this user. When you log into the FCOS VM, you will use that SSH key on the local host.

=== Writing the FCC File
Copy the following example into a text editor:

[source,yaml]
----
variant: fcos
version: 1.0.0
passwd:
  users:                  #this section lists all users
    - name: fcos_user     #the first username goes here
      ssh_authorized_keys:
        - ssh-rsa AAAA... #replace the line starting from "ssh" with the contents of the fcos_user's ssh public key file.
----

Save the file with the name `example.yaml`.

==== FCC Syntax
YAML files must have consistent indentation. Although `fcct` checks for syntax errors, ensure that the indentation matches the above example. Overall, the FCC files must conform to ``fcct``'s schema. For more information on the schema, take a look at the https://github.com/coreos/fcct/blob/master/docs/configuration-v1_0.md[FCC configuration specification].

=== Downloading and Installing FCCT
`fcct`, the Fedora CoreOS Config Transpiler, is a tool that produces a JSON Ignition file from the YAML FCC file. Using this configuration file, an FCOS machine can be told to create users, create filesystems, set up the network, install systemd units, and more.

Download the latest version of `fcct` and the detached signature from the https://github.com/coreos/fcct/releases[releases page].

Import the http://coreos.com/security/app-signing-key/[CoreOS Application Signing Key] into your GPG keyring to verify the downloaded application:

`gpg --import <key>`

`gpg --verify <fcct detatched signature file> <fcct binary>`

Once the download is verified, change the permissions to make it executable:

`chmod +x <fcct binary>`

Run fcct and pipe the output to a file:

`fcct --input example.yaml > example.ign`

The `example.ign` file is ready to be used by FCOS to boot into a VM.

=== Downloading and Extracting the FCOS VM Image
Go to the https://getfedora.org/coreos/download/[download page] to retrieve the latest FCOS qcow file.

Extract the file. Assuming that the downloaded file is called `fedora-coreos-qemu.qcow2.xz`, the command would be the following:


`unxz fedora-coreos-qemu.qcow2.xz`

Ensure the correct ownership of the file:

`chown fcos_user:kvm fedora-coreos-qemu.qcow2`

TIP: The above example assumes that you have created the fcos_user on your local machine. If you did not, replace fcos_user with the user that will boot FCOS on the local host.

=== Booting FCOS in a VM with the Ignition File
To boot FCOS with the Ignition file, you must specify the Ignition file to the hypervisor. In the case of QEMU, do so with the `-fw_cfg` parameter. This sets the `opt/com.coreos/config` key in the QEMU firmware configuration device.

For example:

[source,bash]
----
qemu-system-x86_64 -machine accel=kvm -m 2048 -cpu host -nographic \
	-drive if=virtio,file=path/to/fedora-coreos-qemu.qcow2 \
	-device virtio-rng-pci \
	-fw_cfg name=opt/com.coreos/config,file=path/to/ignition-config.ign
----
Once FCOS boots, it will display the IP address of the VM.

You can then SSH into the FCOS VM as `fcos_user`:

`ssh fcos_user@<ip address>`

NOTE: Once FCOS boots and ingests the Ignition file, you cannot change its configuration. The easiest way to start over is to delete the VM image, re-create the Ignition file (with corrections), and boot with the new image.

Congrats! You are now ready to run some link://running-containers.html[containers]!
