= Live ISO and PXE image reference

== Passing the PXE rootfs to a machine

The Fedora CoreOS PXE image includes three components: a `kernel`, an `initramfs`, and a `rootfs`. All three are mandatory and the live PXE environment will not boot without them.

There are multiple ways to pass the `rootfs` to a machine:

- Specify only the `initramfs` file as the initrd in your PXE configuration, and pass an HTTP(S) URL for the `rootfs` using the `coreos.live.rootfs_url=` kernel argument. This method requires 2 GiB of RAM and an HTTP(S) server. This is the recommended option unless you have special requirements.
- Specify both `initramfs` and `rootfs` files as initrds in your PXE configuration. This can be done via multiple `initrd` directives, or using additional `initrd=` parameters as kernel arguments. This method does not require an HTTP(S) server, since the `rootfs` can be served via TFTP, but is slower and requires 4 GiB of RAM.
- Concatenate the `initramfs` and `rootfs` files together, and specify the combined file as the initrd. This method is slower and requires 4 GiB of RAM.

== Passing network configuration to a live ISO or PXE system

On Fedora CoreOS, networking is typically configured via https://developer.gnome.org/NetworkManager/stable/nm-settings-keyfile.html[NetworkManager keyfiles]. If your network requires special configuration such as static IP addresses, and your Ignition config fetches resources from the network, you cannot simply include those keyfiles in your Ignition config, since that would create a circular dependency.

Instead, you can use `coreos-installer iso customize` or `coreos-installer pxe customize` with the `--network-keyfile` option to create a customized ISO image or PXE `initramfs` image which applies your network settings before running Ignition. For example:

[source,bash,subs="attributes"]
----
coreos-installer iso customize --network-keyfile custom.nmconnection -o custom.iso \
    fedora-coreos-{stable-version}-live.x86_64.iso
----

If you're PXE booting and want to keep your network settings separate from the Fedora CoreOS `initramfs` image, you can also use the lower-level `coreos-installer pxe network wrap` command to create a separate initrd image, and pass that as an additional initrd. For example, run:

[source,bash]
----
coreos-installer pxe network wrap -k custom.nmconnection -o network.img
----

and then use a PXELINUX `APPEND` line similar to:

[source,subs="attributes"]
----
APPEND initrd=fedora-coreos-{stable-version}-live-initramfs.x86_64.img,fedora-coreos-{stable-version}-live-rootfs.x86_64.img,network.img ignition.firstboot ignition.platform.id=metal
----

== Passing kernel arguments to a live ISO system

If you want to modify the default kernel arguments of a live ISO system, you can use the `--live-karg-{append,replace,delete}` options to `coreos-installer iso customize`. For example, if you want to enable simultaneous multithreading (SMT) even on CPUs where that is insecure, you can run:

[source,bash,subs="attributes"]
----
coreos-installer iso customize --live-karg-delete mitigations=auto,nosmt -o custom.iso \
    fedora-coreos-{stable-version}-live.x86_64.iso
----

== Extracting PXE artifacts from a live ISO image

If you want the Fedora CoreOS PXE artifacts and already have an ISO image, you can extract the PXE artifacts from it:

[source,bash,subs="attributes"]
----
podman run --security-opt label=disable --pull=always --rm -v .:/data -w /data \
    quay.io/coreos/coreos-installer:release iso extract pxe \
    fedora-coreos-{stable-version}-live.x86_64.iso
----

The command will print the paths to the artifacts it extracted.

== Using the minimal ISO image

In some cases, you may want to boot the Fedora CoreOS ISO image on a machine equipped with Lights-Out Management (LOM) hardware. You can upload the ISO to the LOM controller as a virtual CD image, but the ISO may be larger than the LOM controller supports.

To avoid this problem, you can convert the ISO image to a smaller _minimal ISO image_ without the `rootfs`. Similar to the PXE image, the minimal ISO must fetch the `rootfs` from the network during boot.

Suppose you plan to host the `rootfs` image at `https://example.com/fedora-coreos-{stable-version}-live-rootfs.x86_64.img`. This command will extract a minimal ISO image and a `rootfs` from an ISO image, embedding a `coreos.live.rootfs_url` kernel argument with the correct URL:

[source,bash,subs="attributes"]
----
podman run --security-opt label=disable --pull=always --rm -v .:/data -w /data \
    quay.io/coreos/coreos-installer:release iso extract minimal-iso \
    --output-rootfs fedora-coreos-{stable-version}-live-rootfs.x86_64.img \
    --rootfs-url https://example.com/fedora-coreos-{stable-version}-live-rootfs.x86_64.img \
    fedora-coreos-{stable-version}-live.x86_64.iso \
    fedora-coreos-{stable-version}-live-minimal.x86_64.iso
----
