= Configuring FCOS to Use a Static IP Address
By default, an FCOS instance will attempt to grab a DHCP address from the local network. However, if you need FCOS to use a static IP address, you can do so by specifying the NetworkManager configuration in the Ignition configuration file.

As with any custom configuration on FCOS, you can write specific files in the xref:ign-storage.adoc[`storage` node] of the Ignition file.

The following snippet shows how to assign a static configuration to `enp1s0`:

NOTE: FCOS uses https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/[predictable interface names] by https://lists.fedoraproject.org/archives/list/coreos-status@lists.fedoraproject.org/thread/6IPTZL57Z5NLBMPYMXNVSYAGLRFZBLIP/[default]. Please take care to use the correct interface name for your hardware.

* static IP: `192.0.2.10/24`
* gateway: `192.0.2.1`
* DNS: `192.168.124.1;1.1.1.1;8.8.8.8`
* DNS search domain: `redhat.com`

.Example assignment of static IP address
[source, yaml]
----
variant: fcos
version: 1.2.0
storage:
  files:
    - path: /etc/NetworkManager/system-connections/enp1s0.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          type=ethernet
          id='Custom interface'
          interface-name=enp1s0

          [ethernet]
          mac-address=<insert MAC address>

          [ipv4]
          method=manual
          addresses=192.0.2.10/24
          gateway=192.0.2.1
          dns=192.168.124.1;1.1.1.1;8.8.8.8
          dns-search=redhat.com
----
NOTE: Additional parameters for NetworkManager key files can be found in the https://developer.gnome.org/NetworkManager/stable/settings-connection.html[NetworkManager documentation].
