= Tutorials

The following tutorials are focused on helping you get started with Fedora CoreOS by learning how to automatically configure (or provision) an instance on first boot. Each tutorial has its roots in the previous one thus it is recommended to follow them sequentially.

If you don't know what Fedora CoreOS is, you can refer to the xref:faq.adoc[FAQ] for more information.

NOTE: If you need any help or need to ask any questions while going through those tutorials, please join the irc://irc.freenode.org/#fedora-coreos[IRC channel], or join our https://discussion.fedoraproject.org/c/server/coreos[discussion board]. If you find any issue in the tutorial, please report them in the https://github.com/coreos/fedora-coreos-docs/issues[fedora-coreos-docs issue tracker].

xref:tutorial-setup.adoc[Initial setup]: Setup instructions that must be completed first to be able to follow the tutorials.

xref:tutorial-autologin.adoc[Enabling autologin and custom hostname]: In this tutorial, you will write your first Ignition config and start a Fedora CoreOS instance with it.

xref:tutorial-services.adoc[Starting a service on first boot]: In this tutorial, you will learn how to start a custom script via a systemd unit on the first boot of a Fedora CoreOS instance.

xref:tutorial-containers.adoc[SSH access and starting containers]: In this tutorial, you will learn how to start a container at first boot with podman.

xref:tutorial-updates.adoc[Testing Fedora CoreOS updates]: In this tutorial, you will learn how automatic updates are handled in Fedora CoreOS and how to rollback in case of failures.

xref:tutorial-user-systemd-unit-on-boot.adoc[Launching a user-level systemd unit on boot] There are times when it’s helpful to launch a user-level systemd unit without having to log in. This tutorial demonstrates creating a user-level systemd unit that launches on boot. 
