:experimental:
= Getting Hands-on with Fedora CoreOS

== Prerequisites:

- You have basic knowledge of what Fedora CoreOS is.
- You have libvirtd installed and active on your system.
- This guide is written targeting a Linux environment with a working `libvirt / kvm` setup.

== Let's get Started:

First of all, We would have to download an Official Stable Virtual QEMU xz archive [.qcow.xz], which you can download from https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable[here].

We've downloaded the archive, Now we would have to verify it by clicking on `Verify signature and SHA256` and Download the checksum file and signature and placing both files in the same directory as the Disk image and follow the instructions mentioned there to ensure the integrity of the archive.

Once the archive is verified, We can extract it with:

[source,bash]
----
xz -d [archive_name]
----

Along with the extracted `.qcow2` archive, you would also need two other programs in order to transpile and validate the ignition scripts, which are:

- fcct : Fedora CoreOS Config Transpiler.
- ignition-validate : A tool to validate a config for ignition.

You can do so by using your favourite package manager, If you're using Fedora as your Host Operating System.
You can install it by using dnf:

[source,bash]
----
dnf install -y fcct ignition-validate
----

If these are not packaged by your distribution, you can use them in a container by using either podman or docker.
You can find them here: https://quay.io/repository/coreos/fcct[fcct] and https://quay.io/repository/coreos/ignition-validate[ignition-validate]

You can use them as following:

[source,bash]
----
podman/docker run --rm -i quay.io/coreos/ignition-validate - < myconfig.ign
----

Or get the Binaries and Source here, https://github.com/coreos/fcct/releases[fcct] and https://github.com/coreos/ignition/releases[ignition-validate]

Once you have them, we can get started with writing our first Ignition file.

== What is Ignition:

Ignition files are used to customize a delivered artifact which is a disk image in our case.

Fedora CoreOS uses Ignition to provision a node in an automated fashion. Ignition config files are written in JSON and typically not user friendly.
For that reason Fedora CoreOS offers the Fedora CoreOS Config Transpiler (also known as FCCT) that will create Ignition configs from a more user friendly format.
Additionally the ignition-validate tool can be used to verify Ignition configs and catch issues before launching a machine.

== First Ignition config via Fedora CoreOS Config Transpiler

Let's create a very simple FCCT config that will perform the following actions:

- Add a systemd dropin to override the default `serial-getty@ttyS0.service`. The override will make the service automatically log the `core` user in to the serial console of the booted machine.
- Place a file at `/etc/zincati/config.d/90-disable-auto-updates.toml` to https://github.com/coreos/zincati/blob/master/docs/usage/auto-updates.md#disabling-auto-updates[disable automatic updates] while we're working on the booted machine for the guide.

We can create a simple FCCT config file named `fcct-simple.yaml` now as:

[source,yaml]
----
variant: fcos
version: 1.1.0
systemd:
  units:
    - name: serial-getty@tty0.service
      dropins:
      - name: autologin-core.conf
        contents: |
          [Service]
          # Override Execstart in main unit
          ExecStart=
          # Add new Execstart with `-` prefix to ignore failure`
          ExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM
storage:
  files:
    - path: /etc/zincati/config.d/90-disable-auto-updates.toml
      contents:
        inline: |
          [updates]
          enabled = false
----

Now we will use `fcct` utility to convert that into an Ignition config.

[source,bash]
----
$ fcct --pretty --strict fcct-simple.yaml --output simple.ign
----

The `fcct` utility will now generate an ign config as `simple.ign`, which will have the following content:
[source,json]
----
{
  "ignition": {
    "version": "3.0.0"
  },
  "storage": {
    "files": [
      {
        "path": "/etc/zincati/config.d/90-disable-auto-updates.toml",
        "contents": {
          "source": "data:,%5Bupdates%5D%0Aenabled%20%3D%20false%0A"
        }
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\nTTYVTDisallocate=no\n",
            "name": "autologin-core.conf"
          }
        ],
        "name": "serial-getty@ttyS0.service"
      }
    ]
  }
}
----

Luckily fcct outputs valid Ignition configs.
However, if you are tweaking the config after fcct, or otherwise providing hand edited Ignition configs you'll want to always use ignition-validate to perform some verification on the config.
We'll do that now to illustrate how:

[source,bash]
----
[host]$ ignition-validate --version
Ignition 2.4.1
[host]$ ignition-validate ./simple.ign && echo 'success!'
----

== Booting Fedora CoreOS: Simple Provisioning Scenario

Given that we've now created an Ignition config. Let's try to boot a VM with an image and that config.
For this lab we'll use the qemu image but you should be able to use that Ignition config with any of the artifacts that are published for a Fedora CoreOS release.

In this case we'll use libvirt/qemu/kvm to boot directly into Fedora CoreOS from the qemu image.

[source,bash]
----
[host]$ chcon --verbose unconfined_u:object_r:svirt_home_t:s0 simple.ign
[host]$ virt-install --name=fcos --vcpus=2 --ram=2048 --import \
            --network=bridge=virbr0 --graphics=none \
            --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${PWD}/simple.ign" \
            --disk=size=20,backing_store=${PWD}/fedora-coreos[stream_version].qcow2
----

*Note:* You would have to replace [stream-version] with the archive name.

*Note:* We used chcon here to set appropriate SELinux file contexts on the Ignition config file so that the resulting process would be able to access the file.

The `virt-install` command will start an instance named `fcos` from the `fedora-coreos-[stream_version]` image using the `simple.ign` Ignition config.
It will auto-attach the serial console of the machine so you'll be able to see the image bootup messages.
Also of note is that it uses the `backing_store` option to `virt-install --disk` so it won't write to the download image, but rather a new disk image that can be easily thrown away.

Once the machine is booted up you should see a few promps and then you should be automatically logged in and presented with a bash shell:

[source,bash]
----
[  OK  ] Started RPM-OSTree System Management Daemon.

Fedora CoreOS preview [stream_version]
Kernel 5.4.7-200.fc31.x86_64 on an x86_64 (ttyS0)

eth0: 192.168.122.20 fe80::5054:ff:feb2:e7f9
localhost login: core (automatic login)

[core@localhost ~]$
----

*Note:* IP address and Kernel version can differ.

Magic? Yes! The systemd dropin was created and we were automatically logged in to the terminal.
You can see the full configuration for serial-getty@ttyS0.service by using
[source,bash]
----
systemctl cat serial-getty@ttyS0.service.
----

We can also check that the zincati configuration file got created by Ignition:

[source,bash]
----
[core@localhost]$ cat /etc/zincati/config.d/90-disable-auto-updates.toml

[updates]
enabled = false
----

== Exploring Fedora CoreOS Internals

Once you have access to the console of the machine you can browse around a bit to see some of the different pieces of the operating system.
For example, even though this is an OSTree based system it was still composed via RPMs and you can inspect the system to see what it was composed of by using rpm:

[source,bash]
----
[core@localhost]$ rpm -q ignition kernel moby-engine podman systemd rpm-ostree zincati
ignition-2.1.1-3.git40c0b57.fc31.x86_64
kernel-5.4.7-200.fc31.x86_64
moby-engine-18.09.8-2.ce.git0dd43dd.fc31.x86_64
podman-1.6.2-2.fc31.x86_64
systemd-243.5-1.fc31.x86_64
rpm-ostree-2019.7-1.fc31.x86_64
zincati-0.0.6-1.fc31.x86_64
----

You can also inspect the current revision of Fedora CoreOS:

[source,bash]
----
[core@localhost]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
* ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 31.20200108.3.0 (2020-01-09T21:51:07Z)
                    Commit: 113aa27efe1bbcf6324af7423f64ef7deb0acbf21b928faec84bf66a60a5c933
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
----

*Note:* The ostree version can differ

And check on zincati.service, which communicates with our update server and tells rpm-ostree when to do an update and to what version to update to:

[source,bash]
----
[core@localhost]$ systemctl status zincati.service | cat
● zincati.service - Zincati Update Agent
   Loaded: loaded (/usr/lib/systemd/system/zincati.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-20 20:01:11 UTC; 2min 9s ago
     Docs: https://github.com/coreos/zincati
 Main PID: 1063 (zincati)
    Tasks: 2 (limit: 2297)
   Memory: 11.4M
   CGroup: /system.slice/zincati.service
           └─1063 /usr/libexec/zincati agent -v

Jan 20 20:01:11 localhost systemd[1]: Started Zincati Update Agent.
Jan 20 20:01:11 localhost zincati[1063]: [INFO ] starting update agent (zincati 0.0.6)
Jan 20 20:01:14 localhost zincati[1063]: [INFO ] Cincinnati service: https://updates.coreos.stg.fedoraproject.org
Jan 20 20:01:14 localhost zincati[1063]: [INFO ] agent running on node 'ead8e3b8ead045dcb36c04bc7be0acbc', in update group 'default'
Jan 20 20:01:14 localhost zincati[1063]: [WARN ] initialization complete, auto-updates logic disabled by configuration
----

*Note:* You can see from the "auto-updates logic disabled by configuration" message that zincati properly picked up the configuration to disable updates that was placed in /etc/zincati/config.d/90-disable-auto-updates.toml.

One other interesting thing to do is view the logs from Ignition in case there is anything interesting there you may want to investigate:

[source,bash]
----
[core@localhost]$ journalctl -t ignition | cat
----

And finally, of course you can use the docker (provided by moby-engine rpm) or podman commands to inspect the current state of containers on the system:

[source,bash]
----
[core@localhost]$ podman version
[core@localhost]$ podman info
----

*Note:* You need `sudo` for docker commands. `podman` commands can be run as root or as non-root user.

*Note:* Running `docker` daemon and `podman` at the same time can cause issues and result in expected behaviour.
Here's an https://docs.fedoraproject.org/en-US/fedora-coreos/faq/#_can_i_run_containers_via_docker_and_podman_at_the_same_time[FAQ Entry] describing the issue.

*Note:* Running a `docker` command will cause the docker daemon to be started if it was not already started.

== Taking down the Virtual Machine

Let's now get rid of that VM so we can start again from scratch.
First escape out of the serial console by pressing `CTRL + ]` and then type:

[source,bash]
----
[host]$ virsh destroy fcos
[host]$ virsh undefine --remove-all-storage fcos
----

