= Prerequisites for the tutorials

The following tutorials are focused on helping you get started with Fedora CoreOS by learning how to automatically configure (or provision) an instance on first boot. Each tutorial has its roots in the previous one thus it is recommended to follow them sequentially.

If you don't know what Fedora CoreOS is, you can refer to the xref:faq.adoc[FAQ] for more information.

NOTE: If you need any help or need to ask any questions while going through those tutorials, please join the link:ircs://irc.libera.chat:6697/#fedora-coreos[IRC channel], or join our https://discussion.fedoraproject.org/tag/coreos[discussion board]. If you find any issue in the tutorial, please report them in the https://github.com/coreos/fedora-coreos-docs/issues[fedora-coreos-docs issue tracker].

You should start with the setup instructions from this page as they must be completed first to be able to follow the tutorials.

  * xref:tutorial-autologin.adoc[Enabling autologin and custom hostname]
    ** In this tutorial, you will write your first Ignition config and start a Fedora CoreOS instance with it.
  * xref:tutorial-services.adoc[Starting a service on first boot]
    ** In this tutorial, you will learn how to start a custom script via a systemd unit on the first boot of a Fedora CoreOS instance.
  * xref:tutorial-containers.adoc[SSH access and starting containers]
    ** In this tutorial, you will learn how to start a container at first boot with podman.
  * xref:tutorial-user-systemd-unit-on-boot.adoc[Launching a user-level systemd unit on boot]
    ** There are times when it’s helpful to launch a user-level systemd unit without having to log in. This tutorial demonstrates creating a user-level systemd unit that launches on boot.
  * xref:tutorial-updates.adoc[Testing Fedora CoreOS updates]
    ** In this tutorial, you will learn how automatic updates are handled in Fedora CoreOS and how to rollback in case of failures.

== Virtualization with `libvirt`

These tutorials are written targeting a Linux environment with a working `libvirt` setup and hardware virtualization support via `KVM`. There is however nothing specific to the `libvirt` environment in those tutorials and you can thus try the same configurations on any platform where you have console access (or you can skip to the SSH access tutorial to get remote access).

For instructions to setup `libvirt` and `KVM` you may refer to the https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/[Getting started with virtualization] guide from Fedora. Although this setup guide is focused on Fedora, the tutorials should work on any distribution with `libvirt` installed and running.

== CoreOS tools

For the tutorials, we will need the following tools:

  * Butane: To generate Ignition configuration from Butane config files.
  * `coreos-installer`: To download the latest Fedora CoreOS QCOW2 image.
  * `ignition-validate`: To validate Ignition configuration files.

To keep all configurations files and Fedora CoreOS images in the same place, we will create a new directory to work from:

[source,bash]
----
mkdir ~/coreos
cd ~/coreos
----

=== Setup with `podman` or `docker`

All of the tools required to work with Fedora CoreOS are available from containers hosted on https://quay.io/[quay.io]:

[source,bash]
----
podman pull quay.io/coreos/butane:release
podman pull quay.io/coreos/coreos-installer:release
podman pull quay.io/coreos/ignition-validate:release
----

To make it simpler to type, you may add the following aliases to your shell configuration:

[source,bash]
----
alias butane='podman run --rm --interactive       \
              --security-opt label=disable        \
              --volume ${PWD}:/pwd --workdir /pwd \
              quay.io/coreos/butane:release'

alias coreos-installer='podman run --pull=always            \
                        --rm --interactive                  \
                        --security-opt label=disable        \
                        --volume ${PWD}:/pwd --workdir /pwd \
                        quay.io/coreos/coreos-installer:release'

alias ignition-validate='podman run --rm --interactive       \
                         --security-opt label=disable        \
                         --volume ${PWD}:/pwd --workdir /pwd \
                         quay.io/coreos/ignition-validate:release'
----

You can then use `coreos-installer` to download the latest stable image with:

[source,bash]
----
coreos-installer download -p qemu -f qcow2.xz --decompress
----

To make the tutorial simpler, you should rename the image that we have just downloaded to a shorter name:

[source,bash,subs="attributes"]
----
mv fedora-coreos-{stable-version}-qemu.x86_64.qcow2 fedora-coreos.qcow2
----

You are now ready to proceed with the xref:tutorial-autologin.adoc[first tutorial].

=== Installing via Fedora packages

All three tools (Butane, `coreos-installer`, and `ignition-validate`) are available as Fedora packages:

[source,bash]
----
# Installing the tools
sudo dnf install -y butane coreos-installer ignition-validate

# Downloading the latest Fedora CoreOS stable QCOW2 image
coreos-installer download -p qemu -f qcow2.xz --decompress
----

To make the tutorial simpler, you should rename the image that we have just downloaded to a shorter name:

[source,bash,subs="attributes"]
----
mv fedora-coreos-{stable-version}-qemu.x86_64.qcow2 fedora-coreos.qcow2
----

You are now ready to proceed with the xref:tutorial-autologin.adoc[first tutorial].

=== Manual download

If none of the previous solutions work for you, you can still manually download Fedora CoreOS from https://getfedora.org/en/coreos/download?tab=metal_virtualized&stream=stable[getfedora.org] with:

[source,bash,subs="attributes"]
----
RELEASE="{stable-version}"
curl -O https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/$RELEASE/x86_64/fedora-coreos-$RELEASE-qemu.x86_64.qcow2.xz
curl -O https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/$RELEASE/x86_64/fedora-coreos-$RELEASE-qemu.x86_64.qcow2.xz.sig
----

Once the archive has been downloaded, make sure to verify its integrity by following the instructions available by clicking on the `Verify signature & SHA256` button. You will have to download the checksum file, the signature and Fedora GPG keys to verify your download:

[source,bash]
----
curl https://getfedora.org/static/fedora.gpg | gpg --import
gpg --verify fedora-coreos-$RELEASE-qemu.x86_64.qcow2.xz.sig
----

Once you have verified the archive, you can extract it with:

[source,bash]
----
unxz fedora-coreos-$RELEASE-qemu.x86_64.qcow2.xz
----

To make the tutorial simpler, you should rename the image that we have just downloaded to a shorter name:

[source,bash,subs="attributes"]
----
mv fedora-coreos-{stable-version}-qemu.x86_64.qcow2 fedora-coreos.qcow2
----

You should then download the latest https://github.com/coreos/butane/releases[Butane] and https://github.com/coreos/ignition/releases[ignition-validate] releases from GitHub:

[source,bash,subs="attributes"]
----
# Butane
curl -OL https://github.com/coreos/butane/releases/download/v{butane-version}/butane-x86_64-unknown-linux-gnu
curl -OL https://github.com/coreos/butane/releases/download/v{butane-version}/butane-x86_64-unknown-linux-gnu.asc
gpg --verify butane-x86_64-unknown-linux-gnu.asc
mv butane-x86_64-unknown-linux-gnu butane
chmod a+x butane

# ignition-validate
curl -OL https://github.com/coreos/ignition/releases/download/v{ignition-version}/ignition-validate-x86_64-linux
curl -OL https://github.com/coreos/ignition/releases/download/v{ignition-version}/ignition-validate-x86_64-linux.asc
gpg --verify ignition-validate-x86_64-linux.asc
mv ignition-validate-x86_64-linux ignition-validate
chmod a+x ignition-validate
----

You may then setup aliases for `butane` and `ignition-validate`:

[source,bash]
----
alias butane="${PWD}/butane"
alias ignition-validate="${PWD}/ignition-validate"
----

Or move those commands to a folder in your `$PATH`, for example:

[source,bash]
----
mv butane ignition-validate "${HOME}/.local/bin/"
# Or
mv butane ignition-validate "${HOME}/bin"
----

You are now ready to proceed with the xref:tutorial-autologin.adoc[first tutorial].
