#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that we are not including the kernel headers on the host.

# See
# - https://bugzilla.redhat.com/show_bug.cgi?id=1814719
# - https://gitlab.cee.redhat.com/coreos/redhat-coreos/-/merge_requests/1116

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

if test -d /usr/include/linux; then
   fatal "Error: should not have kernel headers on host"
fi
ok "kernel headers not on host"
