#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify /usr/share/licenses/fedora-coreos-config/LICENSE exists.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! test -f /usr/share/licenses/fedora-coreos-config/LICENSE; then
    fatal missing LICENSE
fi
ok LICENSE
