#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Test some services are enabled or disabled appropriately
for unit in logrotate logrotate.timer; do
    if ! systemctl is-enabled ${unit} 1>/dev/null; then
        fatal "Unit ${unit} should be enabled"
    fi
    ok "Unit ${unit} is enabled as expected"
done
