#!/bin/bash
# This test only runs on FCOS bceause RHCOS does ship `info` which is a
# Requires on a number of RHCOS packages.
# TODO-RHCOS: modify test to check for RHCOS-specific `remove-files` entry
# kola: { "distros": "fcos", "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

# See remove-files in the manifest
if test -d /usr/share/info; then
    fatal "found /usr/share/info"
fi
