#!/bin/bash
# kola: { "distros": "fcos", "exclusive": false }
# This test only runs on FCOS bceause RHCOS does ship `info` which is a
# Requires on a number of RHCOS packages.
# TODO-RHCOS: modify test to check for RHCOS-specific `remove-files` entry

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# See remove-files in the manifest
if test -d /usr/share/info; then
    fatal "found /usr/share/info"
fi
