#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify / has the immutable bit.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! lsattr -d / | grep -qe '--i--'; then
    fatal "missing immutable bit on /"
fi
ok immutable bit
