#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Security scanners complain about world-readable files in /etc/sudoers.d.
# Check file permissions and syntax of /etc/sudoers and /etc/sudoers.d/*.
# https://bugzilla.redhat.com/show_bug.cgi?id=1981979
visudo -c
ok "sudoers files are valid"
