#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

# Make sure files in /usr/lib/systemd/system-generators have exec mode
find /usr/lib/systemd/system-generators -type f | while read -r f; do
    mode=$(stat -c '%a' "${f}")
    if [[ "${mode}" != 555 ]]; then
        fatal "Error: generator is not executable: ${f}. Expected mode 555, found ${mode}"
    fi
done
