#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Make sure files in /usr/lib/systemd/system-generators have exec mode
find /usr/lib/systemd/system-generators -type f | while read f; do
    if ! test -x $f; then
        fatal "Error: generator is not executable: $f"
    fi
done
ok "system-generators are executable"
