#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# https://bugzilla.redhat.com/show_bug.cgi?id=1830280
tmpd=$(mktemp -d)
cd "${tmpd}"
case "$(arch)" in
    x86_64)
        dmesg | grep ' random:' > random.txt
        if ! grep -qe 'crng.*done.*trust.*CPU' <random.txt; then
            sed -e 's/^/# /' < random.txt
            fatal "Error: Failed to find crng trusting CPU"
        fi
        ok "random trust cpu" ;;
    *) echo "Don't know how to test hardware RNG state on arch=$(arch)" ;;
esac
rm -r "${tmpd}"
