#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# check that no files are unlabeled
unlabeled=$(find /var /etc -context '*:unlabeled_t:*')
if [ -n "${unlabeled}" ]; then
    echo "Found unlabeled files:"
    echo "${unlabeled}"
    exit 1
fi
ok no files with unlabeled_t SELinux label
