#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! test -d /etc/yum.repos.d; then
    fatal "Error: not find /etc/yum.repos.d"
fi
ok "have /etc/yum.repos.d"
