#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify /etc/yum.repos.d exists.

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

if ! test -d /etc/yum.repos.d; then
    fatal "Error: not find /etc/yum.repos.d"
fi
ok "have /etc/yum.repos.d"
