#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

ok() {
    echo "ok" "$@"
}

fatal() {
    echo "$@" >&2
    exit 1
}

if ! test -d /etc/yum.repos.d; then
    fatal "Error: not find /etc/yum.repos.d"
fi
ok "have /etc/yum.repos.d"
