#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# See https://github.com/coreos/coreos-assembler/pull/1786
path=/usr/lib/systemd/system-generators/coreos-platform-chrony
mode=$(stat -c '%a' ${path})
if test "${mode}" != 555; then
    fatal "For path ${path} expected mode 555, found ${mode}"
fi
