apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: fedora-coreos-rawhide-on-pull-request
  namespace: coreos-tenant
  labels:
    appstudio.openshift.io/application: fedora-coreos-rawhide
    appstudio.openshift.io/component: fedora-coreos-rawhide
    pipelines.appstudio.openshift.io/type: build
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/coreos/fedora-coreos-config?rev={{revision}}
    build.appstudio.redhat.com/cancel-in-progress: "true"
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "rawhide" && !(files.all.all(f, f.matches("ci/buildroot/")))
  creationTimestamp: null
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/konflux-fedora/coreos-tenant/fedora-coreos-{{target_branch}}:on-pr-{{revision}}
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: build-args-file
    value: build-args.conf
  - name: workingdir-mount
    value: /run/src
  - name: build-platforms
    value:
    - linux/amd64
    - linux/arm64
  - name: image-expires-after
    value: 5d
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:c1b55f02d5c5ea34e3bf3be4015401564646783407d5b6d8f8a21e0db4f49cc8
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-fedora-coreos-rawhide
