# Stream-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=fedora
NAME=fedora-coreos
STREAM=stable
DESCRIPTION=Fedora CoreOS stable
VERSION=44
MUTATE_OS_RELEASE=44
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-44-standard@sha256:929f0392e82cdb4c351acb7116ccdf593915166032e9343f62fd7fa325d5b024
MANIFEST=manifest.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=manifests
IMAGE_CONFIG=image.yaml
