#!/bin/bash
set -euo pipefail

# This script is called very early in the buildah path from build-rootfs
# after inject_yumrepos() to modify the build environment. Example use cases
# are to fast-track fixes or work around bugs.
# Note that any dowloaded packages here needs to be included in lockfiles (the main
# or overrides one).

# Get the newer fedora-repos with gpgkeys in /usr/
# https://github.com/coreos/fedora-coreos-tracker/issues/2172
if [ "$(rpm -q fedora-repos)" == 'fedora-repos-44-1.noarch' ]; then
    # cachi2 is the repo Konflux injects when hermetic build is enabled
    # and if it's there we can just update from it.
    if [ -f "/etc/yum.repos.d/cachi2.repo" ]; then
        sudo dnf update -y fedora-{repos,repos-archive,gpg-keys}
    else
        # else we need to pull from koji for now
        sudo dnf update -y --disablerepo=* \
            https://kojipkgs.fedoraproject.org//packages/fedora-repos/44/2/noarch/fedora-{repos,repos-archive,gpg-keys}-44-2.noarch.rpm
    fi
fi
