# Stream-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=fedora
NAME=fedora-coreos
STREAM=testing-devel
DESCRIPTION=Fedora CoreOS testing-devel
VERSION=44
MUTATE_OS_RELEASE=44
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-44-standard@sha256:86ed9ccc13420103b1f98c2b3587c09d25bb0ec7faaea0ee4b911c6251338a41
MANIFEST=manifest.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=manifests
IMAGE_CONFIG=image.yaml
#BUILDER_IMG_CHUNKER=
#BUILDER_IMG_CHUNKER_MAX_LAYERS=
