# Stream-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=fedora
NAME=fedora-coreos
STREAM=testing-devel
DESCRIPTION=Fedora CoreOS testing-devel
VERSION=43
MUTATE_OS_RELEASE=43
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-43-standard@sha256:84542b433065993f7fdea344ea117a37638ed9345b990de80d5daf164edb9399
MANIFEST=manifest.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=manifests
IMAGE_CONFIG=image.yaml
