### Containerfile.args

# This is the developer default version. In pipelines, this is driven by versionary.
ARG VERSION="42"
# XXX: This should be a digested pull that gets bumped.
# https://gitlab.com/fedora/bootc/tracker/-/issues/34
ARG BUILDER_IMG=quay.io/fedora/fedora-bootc:42
ARG MANIFEST=manifest.yaml

