#!/bin/bash
# kola: { "exclusive": false }
#
# This test checks kernel messages for the occurance of oom-killer
# https://bugzilla.redhat.com/show_bug.cgi?id=1931467

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if dmesg | grep -q oom-killer; then
    fatal "Error: found oom-killer in kernel messages"
fi
