#!/bin/bash
# kola: { "distros": "fcos", "exclusive": false }
# This test only runs on FCOS because the `dnsmasq` service on RHCOS is simply
# disabled, not masked.
# TODO-RHCOS: adapt test to check that `dnsmasq` is in the proper state on RHCOS

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# make sure dnsmasq is masked
# https://github.com/coreos/fedora-coreos-tracker/issues/519#issuecomment-705140528
if [ "$(systemctl is-enabled dnsmasq.service)" != 'masked' ]; then
    fatal "dnsmasq.service systemd unit should be masked"
fi
ok "dnsmasq.service systemd unit is masked"
