#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

# We shouldn't pull this into the transaction by default. See
# https://github.com/coreos/fedora-coreos-config/pull/1088
# https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
if ! systemctl show -p ActiveState network-online.target | grep -q ActiveState=inactive; then
    fatal "Unit network-online.target shouldn't be active"
fi
