#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

# Ensure NetworkManager's internal DHCP client runs by default

fatal() {
    echo "$@" >&2
    exit 1
}

if ! journalctl -b 0 -u NetworkManager --grep=dhcp | grep -q "Using DHCP client 'internal'"; then
  fatal "Error: NetworkManager's internal DHCP client is not running"
fi
