---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/on-push
transformers:
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer1
    suffix: ' && target_branch == "branched"'
    fieldSpecs:
    - kind: PipelineRun
      path: metadata/annotations/pipelinesascode.tekton.dev\/on-cel-expression
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer2
    suffix: "-branched"
    fieldSpecs:
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/application
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/component
    - kind: PipelineRun
      path: spec/taskRunTemplate/serviceAccountName
patches:
  - target:
      kind: PipelineRun
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'fedora-coreos-branched-on-push'
      - op: replace
        path: /spec/params/10/value
        value: false
