---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/on-pull-request
transformers:
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer
    suffix: "-stable"
    fieldSpecs:
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/application
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/component
    - kind: PipelineRun
      path: spec/taskRunTemplate/serviceAccountName
patches:
  - target:
      kind: PipelineRun
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'fedora-coreos-stable-on-pull-request'
      - op: replace
        path: /metadata/annotations/pipelinesascode.tekton.dev~1on-cel-expression
        value: 'event == "pull_request" && target_branch == "stable" && !(files.all.all(f, f.matches("ci/buildroot/") || f.matches(".tekton/fcos-buildroot/")))'
