#!/bin/bash
# This test is currently scoped to only FCOS because the RHCOS version of `iptables`
# is using the `nf_tables` backend.
# TODO: modify this test to check for `nf_tables` backend when FCOS switches.
#       See https://github.com/coreos/fedora-coreos-config/pull/1324
# kola: { "distros": "fcos", "exclusive": false }
set -xeuo pipefail

ok() {
    echo "ok" "$@"
}

fatal() {
    echo "$@" >&2
    exit 1
}

# Make sure we're still on legacy iptables for now
# https://github.com/coreos/fedora-coreos-tracker/issues/676#issuecomment-928028451
if ! iptables --version | grep legacy; then
    iptables --version # output for logs
    fatal "iptables version is not legacy"
fi
ok "iptables still in legacy mode"
