#!/bin/bash
## kola:
##   exclusive: false
#
# Verify default console log level; xref https://github.com/coreos/fedora-coreos-tracker/issues/1244

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

printk=$(cat /proc/sys/kernel/printk)

if ! [[ "$printk" =~ ^4 ]]; then
    fatal "printk: expected console log level 4, found ${printk}"
fi

ok "Found expected printk value "
