# Short term hack to avoid running out of space on aarch64. This should
# save us about 14M. https://github.com/coreos/fedora-coreos-tracker/issues/1637
# This can be removed once we have added a barrier release.
postprocess:
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    rm -vrf /usr/lib/modules/*aarch64/dtb/qcom/
