# Defines the "core" of a Fedora CoreOS like system; basically (ignition, ostree)
# plus other default tweaks.  Things in this file should be something we expect
# basically everyone using both Ignition and (rpm-)ostree to want.
# It may be used as an inheritance base by other projects like Fedora Silverblue or RHCOS.
# One good model is to add fedora-coreos-config as a git submodule.  See:
# https://github.com/coreos/coreos-assembler/pull/639

packages:
  - ignition
  - ignition-grub
  - dracut-network
  # for encryption
  - clevis clevis-luks clevis-dracut clevis-systemd

packages-s390x:
  # for Secure Execution
  - veritysetup

postprocess:
  # We have our own generator for /boot and we don't mount /boot/efi by default
  # thus we don't strictly need systemd-gpt-auto-generator on Fedora CoreOS.
  # With https://github.com/systemd/systemd/issues/13099 fixed, we can consider
  # including it again after more testing. Current known issues are:
  # - systemd-gpt-auto-generator conflicts with Ignition LUKS provisioning on
  #   EFI systems.
  #   See: https://github.com/coreos/fedora-coreos-tracker/issues/2137
  - |
    #!/usr/bin/env bash
    set -x
    # Find the .build-id file and remove it too so we don't have a broken symlink.
    build_id_file=$(find -L /usr/lib/.build-id/ -samefile /usr/lib/systemd/system-generators/systemd-gpt-auto-generator)
    rm -vf $build_id_file /usr/lib/systemd/system-generators/systemd-gpt-auto-generator
