# Scripts for opting into staying on iptables-legacy after migration. Remove
# after the next barrier release.
ostree-layers:
  - overlay/35coreos-iptables

# Default to iptables-nft. Otherwise, legacy wins. We can drop this once/if we
# remove iptables-legacy.
postprocess:
- |
  #!/usr/bin/env bash
  set -xeuo pipefail
  ln -sf /usr/sbin/ip6tables-nft         /etc/alternatives/ip6tables
  ln -sf /usr/sbin/ip6tables-nft-restore /etc/alternatives/ip6tables-restore
  ln -sf /usr/sbin/ip6tables-nft-save    /etc/alternatives/ip6tables-save
  ln -sf /usr/sbin/iptables-nft          /etc/alternatives/iptables
  ln -sf /usr/sbin/iptables-nft-restore  /etc/alternatives/iptables-restore
  ln -sf /usr/sbin/iptables-nft-save     /etc/alternatives/iptables-save
