# This file includes a fixup for kdump on aarch64 AWS instances.
# The issue seems specific to aarch64 AWS instances, but we'll go
# ahead and apply it across the board for aarch64, since that's
# the easiest thing to do. Hopefully the upstream issue will get
# resolved soon.
postprocess:
  - |
    #!/usr/bin/env bash
    # Remove irqpoll from the list of KDUMP_COMMANDLINE_APPEND. This
    # causes issues on aarch64 AWS instances.
    # https://github.com/coreos/fedora-coreos-tracker/issues/1187
    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
