# This manifest is a list of shared workarounds that are needed in both Fedora CoreOS
# and downstreams (i.e. Red Hat CoreOS).

postprocess:
  # Put in the fix for multipathd.socket on releases that haven't been fixed yet.
  # https://bugzilla.redhat.com/show_bug.cgi?id=2008098
  # https://github.com/coreos/fedora-coreos-config/pull/1246
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    # Operate on RHCOS and FCOS. 
    source /etc/os-release
    if [[ ${NAME} =~ "Fedora" ]]; then
        # FCOS: Only operate on releases before F36. The fix has landed
        # in F36+ and there is no need for a workaround.
        [ ${VERSION_ID} -le 35 ] || exit 0
    else 
        # RHCOS: The fix hasn't landed in any version of RHEL yet
        true
    fi
    mkdir /usr/lib/systemd/system/multipathd.socket.d
    cat > /usr/lib/systemd/system/multipathd.socket.d/50-start-conditions.conf <<'EOF'
    # Temporary workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2008098
    [Unit]
    ConditionKernelCommandLine=!multipath=off
    ConditionKernelCommandLine=!nompath
    ConditionPathExists=/etc/multipath.conf
    ConditionVirtualization=!container
    EOF

  # Put in the fix for multipathd.service in dracut on releases that haven't
  # been fixed yet.
  # https://github.com/dracutdevs/dracut/pull/1606
  # https://github.com/coreos/fedora-coreos-config/pull/1233
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    source /etc/os-release
    if [[ ${NAME} =~ "Fedora" ]]; then
        # FCOS: This fix hasn't landed in rawhide (F36) yet,
        # but hopefully will soon.
        [ ${VERSION_ID} -le 36 ] || exit 0
    else 
        # RHCOS: The fix hasn't landed in any version of RHEL yet
        true
    fi
    mkdir /usr/lib/dracut/modules.d/36coreos-multipath-fix
    cat > /usr/lib/dracut/modules.d/36coreos-multipath-fix/90-multipathd-remove-execstop.conf <<'EOF'
    # Temporary workaround for https://github.com/dracutdevs/dracut/pull/1606.
    [Service]
    ExecStop=
    EOF
    cat > /usr/lib/dracut/modules.d/36coreos-multipath-fix/module-setup.sh <<'EOF'
    #!/bin/bash
    # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
    # ex: ts=8 sw=4 sts=4 et filetype=sh
    install() {
        # Temporary workaround for https://github.com/dracutdevs/dracut/pull/1606.
        mkdir -p "$systemdsystemunitdir/multipathd.service.d"
        inst_simple "$moddir/90-multipathd-remove-execstop.conf" \
        "$systemdsystemunitdir/multipathd.service.d/90-multipathd-remove-execstop.conf"
    }
    EOF
    chmod +x /usr/lib/dracut/modules.d/36coreos-multipath-fix/module-setup.sh
