# This manifest is a list of shared workarounds that are needed in both Fedora CoreOS
# and downstreams (i.e. Red Hat CoreOS).

postprocess:
  # Put in the fix for multipathd.service in dracut on releases that haven't
  # been fixed yet.
  # https://github.com/dracutdevs/dracut/pull/1606
  # https://github.com/coreos/fedora-coreos-config/pull/1233
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    source /etc/os-release
    # This has landed in Fedora but not in any version of RHEL yet
    if [[ ${ID} != "rhel" ]]; then
        exit 0
    fi
    mkdir /usr/lib/dracut/modules.d/36coreos-multipath-fix
    cat > /usr/lib/dracut/modules.d/36coreos-multipath-fix/90-multipathd-remove-execstop.conf <<'EOF'
    # Temporary workaround for https://github.com/dracutdevs/dracut/pull/1606.
    [Service]
    ExecStop=
    EOF
    cat > /usr/lib/dracut/modules.d/36coreos-multipath-fix/module-setup.sh <<'EOF'
    #!/bin/bash
    # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
    # ex: ts=8 sw=4 sts=4 et filetype=sh
    install() {
        # Temporary workaround for https://github.com/dracutdevs/dracut/pull/1606.
        mkdir -p "$systemdsystemunitdir/multipathd.service.d"
        inst_simple "$moddir/90-multipathd-remove-execstop.conf" \
        "$systemdsystemunitdir/multipathd.service.d/90-multipathd-remove-execstop.conf"
    }
    EOF
    chmod +x /usr/lib/dracut/modules.d/36coreos-multipath-fix/module-setup.sh
