# Shared with EL 9 (CentOS Stream 9 and RHCOS 9) only

# Backward compatibility: rescue/warn firstboot network config
# coreos-installer placed in /boot. This will drop out in EL11+..
conditional-include:
  - if: id != "fedora"
    include:
      ostree-layers:
        - fedora-coreos-config/overlay.d/11legacy-copy-network

packages:
  # Teaming https://github.com/coreos/fedora-coreos-config/pull/289
  # and http://bugzilla.redhat.com/1758162
  - NetworkManager-team teamd
  # runc is not in C10S
  - runc
