# Here, we include tier-x, but override some key settings.

include: ../fedora-bootc/tier-x/manifest.yaml

# Required by Ignition, and makes the system not compatible with Anaconda.
# Note this deviates from fedora-bootc and means `systemctl enable` doesn't
# work in a container build. We'll have to resolve that issue some other way in
# the future... For more details, see
# https://github.com/CentOS/centos-bootc/issues/167
machineid-compat: false

# This is the historical default and what FCOS currently ships. fedora-bootc
# uses the new `root` value, but migrating FCOS is not that simple...
opt-usrlocal: var
