#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Verify this command exists since it's a hard dependency of ostree's container bits.
skopeo experimental-image-proxy --help

ok skopeo
