#!/bin/bash
set -euo pipefail

for f in /boot/loader/entries/*.conf; do
    options=$(grep '^options ' "$f" | cut -f2- -d' ')

    # If it's already specified, don't touch whatever value is there. That way,
    # users that purposely opted into v2 early keep it. It also makes this
    # script idempotent.
    if grep -q "systemd.unified_cgroup_hierarchy" <<< "$options"; then
        continue
    fi

    # otherwise, make sure we stay on v1
    sed -e "/^options / s/$/ systemd.unified_cgroup_hierarchy=0/" -i "$f"
    echo "$(basename "$f"): injected systemd.unified_cgroup_hierarchy=0"
done
