#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# systemd-resolved should be fully functional on f35+
source /etc/os-release
if [ "$VERSION_ID" -ge "35" ]; then
    if ! grep 'nameserver 127.0.0.53' /etc/resolv.conf; then
        fatal "systemd-resolved stub listener isn't enabled"
    fi
fi
ok services
