#!/bin/bash
# This test only runs on FCOS because `systemd-resolved` is not installed on
# RHCOS
# kola: { "distros": "fcos", "exclusive": false }
set -xeuo pipefail

ok() {
    echo "ok" "$@"
}

fatal() {
    echo "$@" >&2
    exit 1
}

# systemd-resolved should be enabled
if ! systemctl is-enabled systemd-resolved 1>/dev/null; then
    fatal "Unit systemd-resolved should be enabled"
fi
