#!/bin/bash
## kola:
##   exclusive: false

# This test verifies that the rootfs is automatically grown on first boot in the
# default case.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if [ ! -f /run/ignition-ostree-growfs.stamp ]; then
    fatal "rootfs was not grown on first boot"
fi
ok "rootfs grown on first boot"
