#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify systemd-repart.service is masked.

# See https://github.com/coreos/fedora-coreos-config/pull/744

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

if [ "$(systemctl is-enabled systemd-repart.service)" != 'masked' ]; then
    fatal "systemd-repart.service systemd unit should be masked"
fi
ok "systemd-repart.service systemd unit is masked"
