#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Ensure we have tmpfs on /tmp
tmpfs=$(findmnt -n -o FSTYPE /tmp)
if [ "${tmpfs}" != "tmpfs" ]; then
    fatal "Error: Expected tmpfs on /tmp, found: ${tmpfs}"
fi
ok "tmpfs on /tmp"
