#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

# Ensure we have tmpfs on /tmp
tmpfs=$(findmnt -n -o FSTYPE /tmp)
if [ "${tmpfs}" != "tmpfs" ]; then
    fatal "Error: Expected tmpfs on /tmp, found: ${tmpfs}"
fi
