#!/bin/bash

set -euo pipefail

UNIT_DIR="${1:-/tmp}"

have_karg() {
    local arg="$1"
    local cmdline=( $(</proc/cmdline) )
    local i
    for i in "${cmdline[@]}"; do
        if [[ "$i" =~ "$arg=" ]]; then
            return 0
        fi
    done
    return 1
}

write_dropin() {
    local service="$1"; shift
    local args="$1"; shift

    local out_dir="${UNIT_DIR}/${service}.d"
    mkdir -p "${out_dir}"

    # /tmp isn't r/w yet, and the shell needs to cache the here-document
    TMPDIR=/run
    cat > "${out_dir}/10-autologin.conf" <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin core -o '-p -f core' ${args} %I \$TERM
EOF
}

# We can remove this when we fix https://github.com/coreos/fedora-coreos-tracker/issues/220
silence_audit_on_console() {
    mkdir -p /run/sysctl.d
    cat <<'EOF' > /etc/sysctl.d/20-coreos-autologin-kernel-printk.conf
# Raise console message logging level from DEBUG (7) to WARNING (4)
# so that audit messages don't get interspersed on the console that
# may frustrate a user trying to interactively do an install with
# nmtui and coreos-installer.
kernel.printk=4
EOF
}

# Only allow automatic autologin on live systems
if [ ! -e /run/ostree-live ]; then
    exit 0
fi

# Autologin on ISO boots but not PXE boots.  The only way to tell the
# difference is a kernel argument.
if ! have_karg coreos.liveiso; then
    exit 0
fi

# If the user supplied an Ignition config, they have the ability to enable
# autologin themselves.  Don't automatically render them insecure, since
# they might be running in production and booting via e.g. IPMI.
if [ -e /run/ignition.json ] ; then
    exit 0
fi

write_dropin "getty@.service"        "--noclear"
# Also autologin on serial console if someone enables that
write_dropin "serial-getty@.service" "--keep-baud 115200,38400,9600"

# We can remove this when we fix https://github.com/coreos/fedora-coreos-tracker/issues/220
silence_audit_on_console
