---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
nameSuffix: "-on-push"
patches:
  - target:
      kind: PipelineRun
    patch: |-
      - op: add
        path: /metadata/annotations/build.appstudio.redhat.com~1cancel-in-progress
        value: false
      - op: replace
        path: /spec/params/2
        value:
          name: output-image
          value: quay.io/konflux-fedora/coreos-tenant/fedora-coreos-{{target_branch}}:{{revision}}
