#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that bootupd works.

# We generally implement project-owned tests run in the pipeline
# and be able to run the existing bootupd tests.
# See https://github.com/coreos/fedora-coreos-config/pull/677

set -xeuo pipefail

# shellcheck disable=SC1091
. "$KOLA_EXT_DATA/commonlib.sh"

# Not all streams on which this test runs has bootupd on all arches yet. On
# x86_64 and aarch64, we always expect bootupd to be installed. On ppc64le and
# s390x, let's just conditionally check that *if* bootupd is installed, then
# it's functioning as expected. We can harden it more once we've hard cut over
# to 9.4.
check_state_file=
case "$(arch)" in
    aarch64|x86_64)
        # on these arches, we always expect state files to exist
        check_state_file=1
        ;;
    ppc64le)
        # ppc64le has it if built by osbuild, otherwise not
        if [ -e /sysroot/.aleph-version.json ]; then
            check_state_file=1
        fi
        ;& # fallthrough
    *)
        if ! rpm -q bootupd; then
            exit 0
        fi
        ;;
esac

state_file=/boot/bootupd-state.json
if [ -n "${check_state_file}" ] && [ ! -f "${state_file}" ]; then
    fatal "${state_file} not present"
fi

bootupctl status
ok bootupctl
