#!/bin/bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
REPO_ROOT="$(realpath "${SCRIPT_DIR}/..")"

if ! command -v "kustomize" &> /dev/null; then
    echo "Please install kustomize to run this script:"
    echo "https://github.com/kubernetes-sigs/kustomize/releases/"
    exit 1
fi

echo "Generating pipelinerun configuration..."
for event_kustomization in $REPO_ROOT/.tekton/*/*/kustomization.yaml; do
  event_dir=$(dirname "${event_kustomization}")
  event_name=$(basename "${event_dir}")
  stream_dir=$(dirname "${event_dir}")
  stream_name=$(basename "${stream_dir}")
  if [[ "$event_name" = "base" ]] || [[ "$stream_name" = "base" ]]; then
    continue
  fi
  echo -e "  generating ${stream_name}-${event_name} pipelinerun"
  kustomize build "${event_dir}" -o "${event_dir}"
  output_file=$(find ${event_dir}/tekton.dev*)
  kustomize cfg cat "$output_file" > ${output_file/tekton.dev_*_pipelinerun_/}
  rm -f "${output_file}"
done
