apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/jbtrystram/fedora-coreos-config?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "testing-devel"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: jbtrystram-experiments
    appstudio.openshift.io/component: fcos-build-via-podman
    pipelines.appstudio.openshift.io/type: build
  name: fcos-build-via-podman-on-pull-request
  namespace: coreos-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: build-platforms
    value:
    - linux/amd64
    # - linux/arm64
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: .
  - name: privileged-nested
    value: true
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/konflux-fedora/coreos-tenant/fcos-build-via-podman:on-pr-{{revision}}
  pipelineRef:
    params:
    - name: bundle
      value: quay.io/bootc-devel/tekton-catalog/pipeline-buildah-build-bootc-multi-platform-oci-ta@sha256:17ec031131088220ff381c4f74882471ce60905ffe0ee8589481cef475689afb
    - name: name
      value: buildah-build-bootc-multi-platform-oci-ta
    - name: kind
      value: pipeline
    resolver: bundles
  timeouts:
    pipeline: 6h
