#!/bin/bash
# kola: { "exclusive": false }

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# SELinux should be on
enforce=$(getenforce)
if [ "${enforce}" != "Enforcing" ]; then
    fatal "Error: Expected SELinux Enforcing, found ${enforce}"
fi
ok "selinux is Enforcing"
