#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

ok() {
    echo "ok" "$@"
}

fatal() {
    echo "$@" >&2
    exit 1
}

# SELinux should be on
enforce=$(getenforce)
if [ "${enforce}" != "Enforcing" ]; then
    fatal "Error: Expected SELinux Enforcing, found ${enforce}"
fi
ok "selinux is Enforcing"
