#!/bin/bash
# kola: { "exclusive": false }
# Make sure that kdump didn't start (it's either disabled, or enabled but
# conditional on crashkernel= karg, which we don't bake).

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! systemctl show -p ActiveState kdump.service | grep -q ActiveState=inactive; then
    fatal "Unit kdump.service shouldn't be active"
fi
