#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that we don't have swap on zram by default.

# https://github.com/coreos/fedora-coreos-tracker/issues/509
# https://github.com/coreos/fedora-coreos-config/pull/687
#
# We can run this on both FCOS and RHCOS as neither should have a zram device
# enabled by default. (In RHCOS, there is no zram support at all)

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if [ -e /dev/zram0 ]; then
    fatal "zram0 swap device set up on default install"
fi
ok no zram swap by default
