#!/bin/bash
# kola: { "exclusive": false }
# We can run this on both FCOS and RHCOS as neither should have a zram device
# enabled by default. (In RHCOS, there is no zram support at all)

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# make sure we don't default to having swap on zram
# https://github.com/coreos/fedora-coreos-tracker/issues/509
# https://github.com/coreos/fedora-coreos-config/pull/687
if [ -e /dev/zram0 ]; then
    fatal "zram0 swap device set up on default install"
fi
ok no zram swap by default
