#!/bin/bash
# This is a pinning script to keep legacy ifnames on machines that were
# installed on an OS version where `99-default.link` was missing due to
# https://github.com/coreos/fedora-coreos-tracker/issues/484

set -euo pipefail

injected=0

if test -e /usr/lib/systemd/network/99-default.link; then
    echo "unit /usr/lib/systemd/network/99-default.link found, no actions performed"
    exit 0;
fi

for f in /boot/loader/entries/*.conf; do
    options=$(grep '^options ' "$f" | cut -f2- -d' ')

    # If it is already specified, do not touch whatever value is there.
    # This is in order to avoid messing with user customization, and to
    # make the logic idempotent.
    if grep -q "net.ifnames" <<< "$options"; then
        continue
    fi

    # Otherwise, make sure we stay on legacy ifnames.
    sed -e "/^options / s/$/ net.ifnames=0/" -i "$f"
    echo "$(basename "$f"): injected net.ifnames=0"
    injected=1
done

if [[ $injected -eq 0 ]]; then
    echo "existing net.ifnames karg detected, no actions performed"
fi

