#!/bin/bash
set -euo pipefail

# This script update the bootloader using bootupd
# and also detect RAID-1 setups as those requires
# extra steps

if [ -e /dev/disk/by-label/EFI-SYSTEM ]; then
    echo "Found ESP; calling 'bootupctl update'"
    bootupctl update
    exit
fi

# handle RAID case manually since bootupd doesn't support it
# https://github.com/coreos/bootupd/issues/132
i=1
while true; do
    if [ ! -e /dev/disk/by-label/esp-$i ]; then
        break
    fi
    echo "Found ESP (replica $i); updating"
    mount /dev/disk/by-label/esp-$i /boot/efi
    cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
    umount /boot/efi
    i=$((i+1))
done
sync
