#!/usr/bin/bash
set -euo pipefail

IGNITION_INFO=/var/lib/coreos/ignition.info.json
IGNITION_FIRSTBOOT_INFO=/run/ignition.info.json

WARN='\033[0;33m' # yellow
RESET='\033[0m' # reset

# See coreos-ignition-firstboot-complete
is_firstboot=0
if [ -e "${IGNITION_FIRSTBOOT_INFO}" ]; then
    is_firstboot=1
    mkdir -p "$(dirname "${IGNITION_INFO}")"
    mv "${IGNITION_FIRSTBOOT_INFO}" "${IGNITION_INFO}"
fi

mkdir -p /run/issue.d
touch /run/issue.d/30_coreos_ignition_provisioning.issue

d=$(date --date "@$(jq .date "${IGNITION_INFO}")" +"%Y/%m/%d %H:%M:%S %Z")
if [ "${is_firstboot}" == 1 ]; then
    echo "Ignition: ran on ${d} (this boot)" \
        > /run/issue.d/30_coreos_ignition_provisioning.issue
else
    nreboots=$(($(journalctl --list-boots | wc -l) - 1))
    [ "${nreboots}" -eq 1 ] && boot="boot" || boot="boots"
    echo "Ignition: ran on ${d} (at least $nreboots $boot ago)" \
        > /run/issue.d/30_coreos_ignition_provisioning.issue
fi

if jq -e .usercfg "${IGNITION_INFO}" &>/dev/null; then
    echo "Ignition: user-provided config was applied" \
        >> /run/issue.d/30_coreos_ignition_provisioning.issue
else
    echo -e "${WARN}Ignition: no config provided by user${RESET}" \
        >> /run/issue.d/30_coreos_ignition_provisioning.issue
fi

# Our makeshift way of getting /run/issue.d semantics. See:
# https://github.com/coreos/console-login-helper-messages/blob/e06fc88ae8fbcc3a422bc8c686f70c15aebb9d9a/usr/lib/console-login-helper-messages/issue.defs#L8-L17
ln -sf /run/issue.d/30_coreos_ignition_provisioning.issue /etc/issue.d/
