#!/usr/bin/bash

# This script removes the extra `version` field
# which was shipped in a couple of builds
# when switching to the `build` field
# To be removed after the next barrier release.
# see https://github.com/coreos/fedora-coreos-tracker/issues/1724 for more details

set -euo pipefail

ALEPH_FILE=/sysroot/.coreos-aleph-version.json

if ! jq -e 'has("build") and has("version")' ${ALEPH_FILE}; then
    echo "Aleph file does not require fixing"
    exit
fi

echo "Aleph file is invalid; fixing"

# remount /sysroot as writable
mount -o rw,remount /sysroot

# remove field "build"
fixed_aleph=$(jq 'del(.build)' ${ALEPH_FILE})

echo "$fixed_aleph" > ${ALEPH_FILE}

echo "Aleph file is fixed"
