---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/on-pull-request
transformers:
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer1
    suffix: ' && target_branch == "testing"'
    fieldSpecs:
    - kind: PipelineRun
      path: metadata/annotations/pipelinesascode.tekton.dev\/on-cel-expression
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: SuffixTransformer2
    suffix: "-testing"
    fieldSpecs:
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/application
    - kind: PipelineRun
      path: metadata/labels/appstudio.openshift.io\/component
    - kind: PipelineRun
      path: spec/taskRunTemplate/serviceAccountName
patches:
  - target:
      kind: PipelineRun
    patch: |-
      - op: replace
        path: /metadata/name
        value: 'fedora-coreos-testing-on-pull-request'
