#!/bin/bash
set -euo pipefail

# See also coreos-growpart.service.

# https://github.com/coreos/fedora-coreos-tracker/issues/18
# See also image.ks.
# Growpart /, until we can fix Ignition for separate /var
# (And eventually we want ignition-disks)

path=$1
shift

# The use of tail is to avoid errors from duplicate mounts;
# this shouldn't happen for us but we're being conservative.
src=$(findmnt -nvr -o SOURCE "$path" | tail -n1)
majmin=$(findmnt -nvr -o MAJ:MIN "$path" | tail -n1)
devpath=$(realpath "/sys/dev/block/$majmin")
partition=$(cat "$devpath/partition")
parent_path=$(dirname "$devpath")
parent_device=/dev/$(basename "${parent_path}")

# TODO: make this idempotent, and don't error out if
# we can't resize.
growpart "${parent_device}" "${partition}" || true

eval $(blkid -o export "${src}")
# TODO: Add XFS to https://github.com/systemd/systemd/blob/master/src/partition/growfs.c
# and use it instead.
case "${TYPE}" in
    xfs) xfs_growfs /sysroot ;;
    ext4) resize2fs "${src}" ;;
    *) echo "error: Unsupported filesystem for /sysroot: ${TYPE}" 1>&2; exit 1 ;;
esac

touch /var/lib/coreos-growpart.stamp
