#!/bin/bash
set -euo pipefail

# See also coreos-growpart.service.

# https://github.com/coreos/fedora-coreos-tracker/issues/18
# See also image.ks.
# Growpart /, until we can fix Ignition for separate /var
# (And eventually we want ignition-disks)

path=$1
shift

# remove dupes; we'll still error if somehow there are multiple mounts from
# different devices on there... which is then ambiguous what we should do anyway
majmin=$(findmnt -nvr -o MAJ:MIN "$path" | sort | uniq)
devpath=$(realpath "/sys/dev/block/$majmin")
partition=$(cat "$devpath/partition")
parent_path=$(dirname "$devpath")
parent_device=/dev/$(basename "${parent_path}")

# TODO: make this idempotent, and don't error out if
# we can't resize.
growpart "${parent_device}" "${partition}" || true

# this part is already idempotent
xfs_growfs /sysroot

touch /var/lib/coreos-growpart.stamp
