#!/bin/bash
set -xeuo pipefail

# This test only runs on FCOS as OS extensions are implemented differently on RHCOS.
# kola: { "distros": "fcos", "tags": "needs-internet", "platforms": "qemu", "timeoutMin": 15 }
#
# This test ensures that we can install some common tools as OS extensions.
#
# - platforms: qemu
#   - This test should pass everywhere if it passes anywhere.
# - timeoutMin: 15
#   - This is dependent on network and disk speed but we've seen the
#     test take longer than 10 minutes in our aarch64 qemu tests.

. $KOLA_EXT_DATA/commonlib.sh

# Note: This version must be kept up to date for now, since there currently is no 'latest' (or similar) stream
CRIO_VERSION=1.22

declare -A commands=(
  ["cri-o:${CRIO_VERSION}/default"]="crio"
  ["nginx:mainline"]="nginx"
)

rpm-ostree ex module install "${!commands[@]}"
rpm-ostree ex apply-live

failed=""

for m in "${!commands[@]}"; do
  if [[ -z "$(command -v "${commands[$m]}")" ]]; then
    echo "Could not find: ${commands[$m]}"
    failed+=" ${1}"
  fi
done

if [[ -n "${failed}" ]]; then
  fatal "could not install: ${failed}"
fi
ok "successfully installed os rpm module extensions"
