#!/bin/bash
## kola:
##   tags: "platform-independent needs-internet"
##   # This test only runs on FCOS as OS extensions are implemented differently on RHCOS.
##   distros: fcos
##   # This is dependent on network and disk speed but we've seen the
##   # test take longer than 10 minutes in our aarch64 qemu tests.
##   timeoutMin: 15
##   minMemory: 1536
##   description: Verify that we can install some common tools via module 
##     as OS extensions.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Note: This version must be kept up to date for now, since there currently is no 'latest' (or similar) stream
CRIO_VERSION=1.24

declare -A commands=(
  ["cri-o:${CRIO_VERSION}/default"]="crio"
  ["nginx:mainline"]="nginx"
)

rpm-ostree ex module install "${!commands[@]}"
rpm-ostree ex apply-live

failed=""

for m in "${!commands[@]}"; do
  if [[ -z "$(command -v "${commands[$m]}")" ]]; then
    echo "Could not find: ${commands[$m]}"
    failed+=" ${1}"
  fi
done

if [[ -n "${failed}" ]]; then
  fatal "could not install: ${failed}"
fi
ok "successfully installed os rpm module extensions"
