#!/bin/bash
set -xeuo pipefail

# This test only runs on FCOS as OS extensions are implemented differently on RHCOS.
# kola: { "distros": "fcos", "tags": "needs-internet", "platforms": "qemu", "timeoutMin": 15 }
#
# This test ensures that we can install some common tools as OS extensions.
#
# - timeoutMin: 15
#   - This is dependent on network and disk speed but we've seen the
#     test take longer than 10 minutes in our aarch64 qemu tests.
# - platforms: qemu
#   - This test should pass everywhere if it passes anywhere.

. $KOLA_EXT_DATA/commonlib.sh

commands=(
  'gdb'
  'htop'
  'strace'
  'tcpdump'
  'tree'
)

# Also try some OS extensions which have host bindings. But these we can only do
# on !rawhide because the archive repo isn't active there.
case "$(get_fcos_stream)" in
    "rawhide") ;;
    *) commands+=('vim') ;;
esac

rpm-ostree install --apply-live "${commands[@]}"

failed=""

for c in "${commands[@]}"; do
  if [[ -z "$(command -v "${c}")" ]]; then
    echo "Could not find: ${c}"
    failed+=" ${1}"
  fi
done

if [[ -n "${failed}" ]]; then
  fatal "could not install: ${failed}"
fi
ok "successfully installed os rpm package extensions"
