---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../on-pull-request
nameSuffix: "-overrides"
patches:
  - target:
      kind: PipelineRun
    patch: |-
      - op: replace
        path: /metadata/annotations/pipelinesascode.tekton.dev~1on-cel-expression
        value: event == "pull_request" && "manifest-lock.overrides*".pathChanged()
